### ISSUE TITLE
Quiet docker image build log

### ISSUE THREAD

**Issue by kiitosu** [aws-powertools/powertools-lambda-layer-cdk#92]
When using the cdk-lambda-powertools-python-layer, executing cdk diff results in extensive Docker image build logs being output. This clutter makes it difficult to find meaningful information in the logs. Is there any way to quiet docker image build log?

Sample logs:

`path /Users/xxxxxxxx/repos/yyyyyyyy/node_modules/cdk-lambda-powertools-python-layer/layer/Python
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM public.ecr.aws/lambda/python:3.8
3.8: Pulling from lambda/python
10f19c591d57: Already exists 
1f9a1bd0ce30: Pull complete 
7fed1efdf3b7: Pull complete 
3b7e16a130c3: Pull complete 
6e4ca4ccb6b9: Pull complete 
5496b38dd996: Pull complete 
Digest: sha256:8563785afb7060bb04db1d765de2b8e78f0c8c79d1a06070e46065d2e9242a8c
Status: Downloaded newer image for public.ecr.aws/lambda/python:3.8
 ---> 5c0d2f2d70e0
Step 2/6 : ARG PACKAGE_SUFFIX=''
 ---> Running in 4af3b4f920ca
 ---> Removed intermediate container 4af3b4f920ca
 ---> b78d4476c44f
Step 3/6 : USER root
 ---> Running in ae068305f31c
 ---> Removed intermediate container ae068305f31c
 ---> 90e882d007d5
Step 4/6 : WORKDIR /tmp
 ---> Running in 19a41bfbe1fa
 ---> Removed intermediate container 19a41bfbe1fa
 ---> ead22162aa00
Step 5/6 : RUN yum update -y && yum install -y zip unzip wget tar gzip
 ---> Running in a7d45700139d
Loaded plugins: ovl
No packages marked for update
Loaded plugins: ovl
`

**Comment by am29d** [comment]
Hey @kiitosu , apologies for the late reply. 

While there is an option to suppress the output with `-q` flag `docker build -q -t foo . `, I can't find any option to pass it to the CDK construct that runs the docker command 🤔 . 

I have submitted a [feature request](https://github.com/aws/aws-cdk/issues/30988), once we have an option to pass the flag, we will update the construct.
