### ISSUE TITLE
Review the build pipeline and tokens

### ISSUE THREAD

**Issue by leandrodamascena** [aws-powertools/powertools-lambda-layer-cdk#96]
We need to review the CDK layer build pipeline as well as the tokens used in the pipeline.

**Comment by dreamorosi** [comment]
Specifically, we should ensure that all the workflows used in the repo follow the org-wide standards in terms of security and best practices.

Likewise, we should make sure that all tokens used in the workflows are audited and centralized. At the moment we have 4 different tokens that need to be reviewed: 1 for npm, 2 for twine, and one that is a GitHub PAT.
